#!/usr/bin/env python3

import sys
path = sys.argv[1]
with open(path, 'r') as file:
    lines = file.read().splitlines()
lines[-1] = 'eula=true'
with open(path, 'w') as file:
    file.write('\n'.join(lines))
